#!/bin/zsh
git submodule add https://github.com/vim-scripts/AnsiEsc.vim.git vimfiles/bundle/AnsiEsc.vim
git submodule add https://github.com/kien/ctrlp.vim.git vimfiles/bundle/ctrip.vim
git submodule add https://github.com/Yggdroot/indentLine.git vimfiles/bundle/indentLine
git submodule add https://github.com/Shougo/neobundle.vim.git vimfiles/bundle/neobundle.vim
git submodule add https://github.com/Shougo/neomru.vim.git vimfiles/bundle/neomru.vim
git submodule add https://github.com/Shougo/neosnippet-snippets.git vimfiles/bundle/neosnippet-snippets
git submodule add https://github.com/Shougo/neosnippet.vim.git vimfiles/bundle/neosnippet.vim
git submodule add https://github.com/scrooloose/nerdtree.git vimfiles/bundle/nerdtree
git submodule add https://github.com/vim-syntastic/syntastic.git vimfiles/bundle/syntastic
git submodule add https://github.com/tomtom/tcomment_vim.git vimfiles/bundle/tcomment_vim
git submodule add https://github.com/Shougo/unite.vim.git vimfiles/bundle/unite.vim
git submodule add https://github.com/flazz/vim-colorschemes.git vimfiles/bundle/vim-colorschemes
git submodule add https://github.com/tpope/vim-endwise.git vimfiles/bundle/vim-endwise
git submodule add https://github.com/tpope/vim-fugitive.git vimfiles/bundle/vim-fugitive
git submodule add https://github.com/nathanaelkane/vim-indent-guides.git vimfiles/bundle/indent-guides
git submodule add https://github.com/tpope/vim-rails.git vimfiles/bundle/vim-rails
git submodule add https://github.com/Shougo/vimshell.vim.git vimfiles/bundle/vimshell_3787e5
git submodule add https://github.com/rhysd/wandbox-vim.git vimfiles/bundle/wandbox-vim
